version: "3.8"

services:
  backend:
    build: .
    image: dino96112/node-app
    container_name: backend
    ports:
      - 49160:5000
    networks:
      - node-network
    environment:
      - NAME=coba
      - HOST=mysqlserver
      - PORT=3306
  backend1:
    build: .
    image: dino96112/node-app
    container_name: backend1
    ports:
      - 49161:5000
    networks:
      - node-network
    environment:
      - NAME=coba
      - HOST=mysqlserver
      - PORT=3306
  mysqlaja1:
    image: mysql
    container_name: mysqlaja1
    ports:
      - 8083:3306
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - node-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysqldata:
    external: true
networks:
  node-network:
    external: true
